### ISSUE TITLE
Actualización de dependencias

### ISSUE THREAD

**Issue by donali98** [donali98/MakeQReader#2]
Las librerías de navegación y algunas de ciclo de vida sugieren una versión más reciente, favor investigar si dichas actualizaciones generarían algún impacto negativo.
![captura](https://user-images.githubusercontent.com/36904231/87588528-0f7b6200-c6a1-11ea-9d64-0e3c55141a17.PNG)

**Comment by joisgori** [comment]
Luego de realizar la investigación, se ha determinado que actualizar las librerías a sus versiones más recientes no afectaría de ninguna manera el funcionamiento correcto de la aplicación.

**Comment by donali98** [comment]
Entendido, gracias Josué.
