### ISSUE TITLE
Sobre dimensiones del qreader

### ISSUE THREAD

**Issue by Dalcoleas** [donali98/MakeQReader#4]
La librería encargada de generar el QReader para el item del inventario necesita como argumento un cálculo que involucra las dimensiones de la pantalla, necesitamos una forma de obtenerlas ya que la forma tradicional que se usa en una actividad no funciona al momento de querer implementarla en fragmentos.

**Comment by donali98** [comment]
He encontrado la forma, es esta:

`val width = resources.configuration.screenWidthDp
                val height = resources.configuration.screenHeightDp`

**Comment by Dalcoleas** [comment]
Lo tomaré en cuenta para el próximo commit, gracias Donalí
